instance_name = "开发项目"

[log]

[accounts.main]
type = "polymarket_relayer_account"
name = "test"
private_key = "a"          # 放在 secrets.toml 更安全
funder_address = "b"
deposit_wallet = "c"
builder_api = "d"
builder_secret = "e"
builder_pass_phrase = "f"