instance_name = "单元测试模式"
environment = "unitest"
[log]
log_level="DEBUG"

[accounts.main]
type = "polymarket_relayer_account"
name = "test"
private_key = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"          # 放在 secrets.toml 更安全
funder_address = "b"
deposit_wallet = "c"
builder_api = "d"
builder_secret = "e"
builder_pass_phrase = "f"